repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.5.25
  hooks:
  - id: uv-lock  # Keep uv.lock up to date with pyproject.toml
- repo: https://github.com/crate-ci/typos
  rev: v1.29.4
  hooks:
  - id: typos
